# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc0f62428910b28717310ac803000463ccffd752e8f2a8e0fbeb54ca88a9bb9eaa2d45619fced32ec73fad8980b1b1dc538e604d6716a0bc12af81f23a65be74

test:
  secret_key_base: 8ee39839d9f1f29b19814446cc155ed603bcaf6b92a7a14b6eb3a659621805332a0fd5ca97c6f721202efa6a433e11dffeba7091e9ec424cdba5b41f89d488b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
